# Generated by Django 3.2.20 on 2023-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
